---

# required packages
- name: Ensure dependencies are installed
  apt: "pkg={{ item }} state=present"
  with_items:
   - build-essential
   - automake
   - supervisor
   - ntp
   - ntpdate
   - alsa-utils
   - libvlc-dev
   - vlc-nox
   - libasound2-dev
   - libmagickwand-dev
   # note: on debian jessie the libzmq3-dev package installs version 4.0.5+
   - libzmq3-dev
  changed_when: False
  become: yes
  become_user: root
  when: ansible_os_family == 'Debian'

# users & groups
- group: name={{ encoder_group }} state=present gid=2002
- user: name={{ encoder_user }}
        comment="odr user"
        shell=/bin/bash
        uid=2002
        group={{ encoder_group }}
        groups="sudo,audio"

# directories & files
- name: Create log directory
  file: path={{ encoder_log_dir }} state=directory owner={{ encoder_user }} group={{ encoder_group }}

##
# audio interface specific tasks
- include: install-asihpi.yml
  tags: install,interface,asihpi
  become: yes
  when: encoder_audio_interface is defined and encoder_audio_interface == 'asi5211'

##
# sound-system specific tasks
- include: install-jackd.yml
  tags: install,soundsystem,jackd
  become: yes
  become_user: "{{ encoder_user }}"
  when: encoder_soundsystem is defined and encoder_soundsystem == 'jackd'

- include: uninstall-jackd.yml
  tags: install,soundsystem,jackd
  become: yes
  become_user: "{{ encoder_user }}"
  when: encoder_soundsystem is defined and encoder_soundsystem != 'jackd'

## source installs
# fdk-aac
- include: install-fdk-aac.yml
  tags: install,odr,fdk-aac
  become: yes
  become_user: "{{ encoder_user }}"

# ODR AudioEnc
- include: install-odr-audioenc.yml
  tags: install,odr,odr-audioenc
  become: yes
  become_user: "{{ encoder_user }}"

# ODR PadEnc
- include: install-odr-padenc.yml
  tags: install,odr,odr-padenc
  become: yes
  become_user: "{{ encoder_user }}"

# encoder configuration
- include: configuration.yml
  tags: configuration
  become: yes
  become_user: root
  when: encoder_service_enabled is defined and encoder_service_enabled == true

# dls metadata update (ftp)
- include: dls-ftp.yml
  tags: dls,ftp
  become: yes
  become_user: root
  when: encoder_ftp_enabled is defined and encoder_ftp_enabled == true

# digris service api client
- include: service-client.yml
  tags: service,service-client
  become: yes
  become_user: root
  when: encoder_service_client_enabled is defined and encoder_service_client_enabled == true

# include autossh reverse tunnel
#- include: service-autossh.yml
#  tags: system,autossh
#  become: yes
#  become_user: root
#  when: encoder_service_autossh_enabled is defined and encoder_service_autossh_enabled == true

# include pre-login info (/etc/issues)
- include: pre-login-info.yml
  tags: system,pre-login-info
  become: yes
  become_user: root
  when: encoder_pre_login_info_enabled is defined and encoder_pre_login_info_enabled == true

# include source monitoring
- include: install-source-monitoring.yml
  tags: system,source-monitoring
  become: yes
  become_user: root
  when: encoder_source_monitoring_enabled is defined and encoder_source_monitoring_enabled == true

# post-install tasks
- include: post-install.yml
  tags: system,install,post-install
  become: yes
  become_user: root
